version: "3.9"

services:
  web:
    build: .
    container_name: todo
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000" # Map port 8000 on host to port 8000 on container
    environment:
      - PORT=8000 # Set the PORT environment variable to 8000
    volumes:
      - .:/app
