# Generated by Django 4.1.7 on 2023-03-20 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todomodel',
            old_name='completed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
