# Generated by Django 4.1.7 on 2023-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_date_todomodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
