# Generated by Django 4.1.7 on 2023-03-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todomodel1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoModel1',
        ),
    ]
