# Generated by Django 4.1.7 on 2023-03-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_todomodel1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoModel1',
        ),
    ]
